// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2w7WL5bm-FuQzweKgkjX49jLLt593GDA',
    appId: '1:780709004461:web:ee58a61faeb21f8f32b224',
    messagingSenderId: '780709004461',
    projectId: 'smart-ev-f653f',
    authDomain: 'smart-ev-f653f.firebaseapp.com',
    databaseURL: 'https://smart-ev-f653f-default-rtdb.firebaseio.com',
    storageBucket: 'smart-ev-f653f.appspot.com',
    measurementId: 'G-NR0BP53NPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNDG_plRr48x2BYKKE_xTE8hFNObt7QJM',
    appId: '1:780709004461:android:89f05100a8e5d35932b224',
    messagingSenderId: '780709004461',
    projectId: 'smart-ev-f653f',
    databaseURL: 'https://smart-ev-f653f-default-rtdb.firebaseio.com',
    storageBucket: 'smart-ev-f653f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0takA5B907eRmnrC4K6i_qzPdXDIV478',
    appId: '1:780709004461:ios:1aa255e0b149288432b224',
    messagingSenderId: '780709004461',
    projectId: 'smart-ev-f653f',
    databaseURL: 'https://smart-ev-f653f-default-rtdb.firebaseio.com',
    storageBucket: 'smart-ev-f653f.appspot.com',
    iosClientId:
        '780709004461-mgipvgto5mkcoi08hufs0hjojrhk8c4p.apps.googleusercontent.com',
    iosBundleId: 'com.harsh.smartRikshaw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0takA5B907eRmnrC4K6i_qzPdXDIV478',
    appId: '1:780709004461:ios:1aa255e0b149288432b224',
    messagingSenderId: '780709004461',
    projectId: 'smart-ev-f653f',
    databaseURL: 'https://smart-ev-f653f-default-rtdb.firebaseio.com',
    storageBucket: 'smart-ev-f653f.appspot.com',
    iosClientId:
        '780709004461-mgipvgto5mkcoi08hufs0hjojrhk8c4p.apps.googleusercontent.com',
    iosBundleId: 'com.harsh.smartRikshaw',
  );
}
